name: Code Quality Checks

on:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  codeQuality:
    name: Eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Check with eslint
        id: eslint-run
        run: |
          npx eslint
      - name: Check with prettier
        id: prettier-run
        run: |
          npx prettier --check .
