name: Code Style fix

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:


# Allow this job to clone the repo and create a page deployment
permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  codeStyle:
    name: Prettier
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }} || ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies
        run: npm install -g prettier
      - name: Run Prettier
        id: prettier-run
        run: |
          prettier --check . --ignore-unknown --write 
          echo "filecount=$(git status -s -uno | wc -L)" >> $GITHUB_OUTPUT
      - name: Commit changes
        if: ${{ steps.prettier-run.outputs.filecount > 0 }} 
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions - Prettier"
          git add .
          git commit -m "Run Prettier"
          git push
